
name: Documentation

on:
  push:
    branches:
      - main   # or 'master', depending on your default branch
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'   # or your preferred version

      - name: Install dependencies
        run: |
          julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.instantiate()'

      - name: Build and deploy docs
        run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
